#cloud-config

# https://cloudinit.readthedocs.io/en/latest/topics/modules.html
# https://cloudinit.readthedocs.io/en/latest/topics/examples.html

### Users

users:
  - name: ${compute_username}
    ssh_authorized_keys:
      - ${compute_ssh_public_key}
    shell: /usr/bin/bash
    groups: sudo, users, docker
    sudo: "ALL=(ALL) NOPASSWD:ALL"

groups:
  - docker

ssh_pwauth: false

### Packages

apt:
  sources:
    tailscale.list:
      source: deb https://pkgs.tailscale.com/stable/ubuntu $RELEASE main
      keyid: 2596A99EAAB33821893C0A79458CA832957F5868
    docker.list:
      source: deb https://download.docker.com/linux/ubuntu $RELEASE stable
      keyid: 9DC858229FC7DD38854AE2D88D81803C0EBFCD88
    kubernetes.list:
      source: deb https://apt.kubernetes.io/ kubernetes-xenial main
      keyid: 59FE0256827269DC81578F928B57C5C2836F4BEB

packages:
  - build-essential
  - default-jre-headless
  - docker-ce
  - docker-ce-cli
  - emacs-nox
  - fswatch
  - git-extras
  - golang
  - jq
  - keychain
  - kubectl
  - mosh
  - pwgen
  - python
  - python-dev
  - ruby
  - ruby-dev
  - silversearcher-ag
  - socat
  - sshfs
  - swaks
  - tailscale
  - tig
  - tshark
  - uuid
  - zip

package_upgrade: true

### Bootstrap commands

runcmd:
  - "sh -c 'echo ENABLED=0 > /etc/default/motd-news'"
  - iptables -F
  - netfilter-persistent save
  - ufw reset
  - tailscale up -authkey ${tailscale_auth_key}
  - ufw allow in on tailscale0
  - ufw allow 22/tcp
  - ufw allow 41641/udp
  - ufw default deny incoming
  - ufw default allow outgoing
  - ufw reload
  - ufw enable
  - systemctl restart ssh
  - systemctl restart docker
